FROM golang:1.22.2
ENV DOCKERVERSION=20.10.2
ENV DOCKERARCH=x86_64

WORKDIR /usr/src/app/cmd/executor

# Docker
RUN curl -fsSLO https://download.docker.com/linux/static/stable/${DOCKERARCH}/docker-${DOCKERVERSION}.tgz \
    && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker \
    && rm docker-${DOCKERVERSION}.tgz

RUN go install github.com/githubnemo/CompileDaemon@latest

RUN groupadd -g 992 docker -r && usermod -a -G docker www-data

CMD CompileDaemon -command="./executor"
