FROM debian
ENV DOCKERVERSION=20.10.2
ENV DOCKERARCH=x86_64

ENV APP_FOLDER="/opt/web"

RUN apt-get update && apt-get install -y nginx \
    sed \
    curl \
    supervisor \
    python3 \
    python3-pip \
    python3-setuptools \
    libpcre3 \
    libpcre3-dev \
    python3-six \
    python3-psutil \
    python3-redis \
    python3-protobuf \
    && apt-get clean

# Docker
RUN curl -fsSLO https://download.docker.com/linux/static/stable/${DOCKERARCH}/docker-${DOCKERVERSION}.tgz \
    && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker \
    && rm docker-${DOCKERVERSION}.tgz

# Python
COPY src/requirements.txt ${APP_FOLDER}/
RUN pip3 install -r ${APP_FOLDER}/requirements.txt

# COMMAND
WORKDIR ${APP_FOLDER}
CMD python3 app.py
