FROM debian
MAINTAINER fabrizio2210

ENV APP_FOLDER="/opt/web"

RUN apt-get update && apt-get install -y nginx \
    npm \
    nodejs

RUN ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log

COPY src/vue/ ${APP_FOLDER}/

RUN cd ${APP_FOLDER}/src/ && \
    npm cache clean -f && \
    rm -rf node_modules package-lock.json && \
    npm install && \
    npm run build && \
    cp -r ../dist/* /var/www/html/

# COMMAND
CMD /usr/sbin/nginx -g 'daemon off;'
