FROM golang:1.22.2
ENV DOCKERVERSION=20.10.2
ENV DOCKERARCH=x86_64

COPY src/go/ /usr/src/app

WORKDIR /usr/src/app/cmd/executor

# Docker
RUN curl -fsSLO https://download.docker.com/linux/static/stable/${DOCKERARCH}/docker-${DOCKERVERSION}.tgz \
    && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker \
    && rm docker-${DOCKERVERSION}.tgz


RUN go build

CMD ./executor
